### ISSUE TITLE
cstdint required in PcmFile.h

### ISSUE THREAD

**Issue by LinuxJedi** [joakimoh/AtomTapeUtils#1]
I could not compile this in GCC 13.2 due to missing definitions for `uint32_t` and alike. This was fixed by adding:

```c
#include <cstdint>
```

Just before `#include "WaveSampleTypes.h"` in `shared/PcmFile.h`

**Comment by joakimoh** [comment]
It worked for me without this include but you're right it should be there. I've added it now. Thanks for telling me!
